### ISSUE TITLE
Syntax Error while Pulling: Missing Repository Objects 

### ISSUE THREAD

**Issue by HuprichT** [sbcgua/mockup_loader#40] opened 2022-08-05 09:38 UTC
Hi, 

today I tried to test this Project. Unfortunately I am not able since there some Errors occuring during Test: 

```
"Use of OS Mockup Loader
data: lo_ex      type ref to cx_static_check,
o_ml TYPE REF TO zif_mockup_loader. "This Object needs reference to Global Class  
  try.
        o_ml = zcl_mockup_loader=>create(
          i_path       = 'C:\Users\XXX\XXX\Testdaten\TD_PC.zip' ).
      catch cx_static_check into lo_ex.
        MESSAGE lo_ex->get_text( ) TYPE 'E'.
  endtry.
```
![image](https://user-images.githubusercontent.com/45813255/183049415-84902ce2-a1b4-43c0-b56e-4dd829c96b9a.png)

After removing and reinstalling the Repo it shows that there are some classes which are not (no longer?) available.

![image](https://user-images.githubusercontent.com/45813255/183049614-3f50408e-23ed-48b2-81fb-ea6963d9d61f.png)

**Comment by TheWirtschaftsmann** [comment] 2022-08-05 10:18
Hi @seniorFreshmen,

I think the problem is that you did not install the pre-requisite package https://github.com/sbcgua/text2tab. It is mentioned under the p. "Installation" in Readme.

Could you please try install the pre-requisite package and try one more time ?

Regards,
Bohdan

**Comment by sbcgua** [comment] 2023-02-09 07:55
closing as resolved

**Closed as completed by sbcgua** 2023-02-09 07:55 UTC
